---
abstract: 'implicit invoker, sort of'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  B::Hooks::OP::Check: 0
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: invoker
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Check: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clkao/invoker.git
version: 0.29_002
